* draft
** todos
- [X] choose shrier quotes
- [X] read Butler, /BTM/
- [ ] read Amin's critique of Butler; 
- [ ] read /CA/ annotations & articles.

** outline
- anti-trans bill titles
  - patriarchal langauge shows an attachment to norms, protecting
    women and children, figures that need to be protected. 
- close reading of Shrier
  - we can begin to parse out some of the deeper contradictions here:
    that free expression only applies to certain kinds of expression. 
  - an example of the kind of reading I don't want to do
- Sedgwick and readings of shame.
  - remember Heather Love's critique: that Sedgwick is still trying to
    make shame a politically viable object.
  - Cassius Adair reading trans erotics in porn.
- Close reading of ML mechanism, and of results.
  - contrast with Butlerian close reading (or do this at top?)
  
** argument (& method?)
This is an essay about ways of reading. 

This is an essay about a machine process, one that you are by now
familiar with, even if you don't know how it works on a technical
level. My goal is to illuminate this machine process by drawing an
analogy between it and human affects of fear and desire, specifically,
what fear implies about desire, in the phobia that the body has toward
its own desire.

The analogy between machines and bodies evokes a longstanding
conflation of the two in the term "Artificial Intelligence," which is
itself an anthropomorphization of machine processes like algorithmic
prediction.[fn:1] My intention is not to do away with this conflation,
but to re-orient some of the terms on which it rests. Information
processing is seen as intelligent, as human-like (it is
anthromoporphized) but with the benefit of being free of the human
body. So let us bring the body back into the machine. This paper
achieves this goal in two ways: by attending to embodied experience of
phobia, and what phobia reveals about desire, and by tracing the
materiality of machine learning processes.

To bring machines and bodies into relation, I enlist the concept of
normativity, and particularly, the attachment to normativity that, I
will show, brings procedures of both desire and of algorithmic
prediction into productive relation. I will take, on the one hand, the
desire for normative gender identities that underlies contemporary
discourses of transphobia, expressed in the anti-trans legislative
movement, and, on the other hand, what happens to data as it is used
to train machine learning models. Across these widely different
domains, I argue, this shared drive toward normativity enables me to
deploy machine learning as an apt tool for studying normativity in
transphobic language.

The investment in normativity is a through line, common ground,
between transphobia and trans affirmation. It is the answer to the
question--What do trans subjects and far right ideologues have in
common? In a more subtle way, it is also an attempt to bring desire
explicitly into computational processing.

** TODO close reading
There are currently 81 legislative bills in Congress that concern
trans people's rights. Below is a list of some of their titles:

#+begin_quote
US HB1064: Ensuring Military Readiness Act of 2023

US HB1276: Protect Minors from Medical Malpractice Act of 2023

US HB10075: Stopping the Mutilation of Children Act of 2024

US HB1399: Protect Children’s Innocence Act

US HB216: My Child, My Choice Act of 2023

US HB1490: Preventing Violence Against Female Inmates Act of 2023
#+end_quote

[I actually need to state in plain terms what the bills are doing
here]

These bills seek to deny trans people access to services and
recognition within various domains, including health, school, prison
and the military.

To assert control over the transgender designation, the text of these
bills circumscribes sex and gender into an immutable and constitutive
relationship. For example, one the bills defines "sex" as "the
biological indication of male or female in the context of reproductive
potential or capacity, including sex chromosomes, naturally occurring
sex hormones, gonads, and nonambiguous internal and external genitalia
present at birth" ("My Child, My Choice Act of 2023"). The same bill
defines "gender" as "an individual’s perception of their own gender or
claimed gender, regardless of the biological sex of the individual." 

As a Queer Studies scholar, I am interested in the assumptions that
such definitions make, in the contradictions that are necessarily
implied by any attempt to naturalize sex as embodied and to define
gender recursively as itself and against "sex."

I will come back to the content of these definitions and the ways they
define sex and gender.

For now, however, I want to acknowledge the logic of transphobia
glaring the surface of these bills, in their titles that invoke the
fear of gender nonconformity as a national threat, from which the
American people (especially children) need protection.

In public discourses, the fear is that transness is contagious, that
it can spread from person to person. This fear, which is popularized
in the now debunked medical diagnosis called "Rapid-onset Gender
Dysphoria," or ROGD, has had a significant influence on public
perception around trans issues, especially as they affect minors. A
popular book by Abigail Shrier, called "Irreversible Damage: The
Transgender Craze Seducing Our Daughters" focuses on how this
contagion affects teenagers assigned female at birth who, she argues,
succumb to social pressures from peers and influencers to desire
transition.

(Actually, another fascinating thing about Shrier's book is how she
warns again and again against a danger which is never explicitly
articulated, but must so obvious as to be assumed by her readers, that
gender transition is akin to bodily mutilation.)

Shrier embeds her assumptions in a highly ironic tone. Take the
following example, where Shrier distinguishes between respecting
expressions of gender against that of patriotism:

#+begin_quote
if the government can’t force students to salute a flag, the
government can’t force a healthcare worker to utter a particular
pronoun. In America, the government can’t make people say things--not
even for the sake of politeness. Not for any reason at all. (xx)
#+end_quote

Here, Shrier apparently seems to be saying that, just as the
government cannot compel people to express loyalty to the country's
symbols, so it cannot compel respect (what she calls "politeness") for
a person's preferred gender designation. Through this comparision to
patriotism, and the framing of the issue around expression, she
suggests that forcing pronoun usage would be fascist. Which is a
strange way to make a point to what (I imagine) is a largely
conservative readership.

Unless, reading this statement through the frame of irony, the point
is precisely that some kinds of expression should be free while others
should not. That citizens /do/ have the right to question each other's
genders, but not to question the flag. In plain terms, then, the
sentence would be saying something like, "look, our government so
loves your freedom, that it cannot even force you to show respect for
it." And, it follows, if you are free to disrespect such a
government, then you surely cannot be obligated to honor someone's
pronouns. In this reading, we can trace a direct line between an
investment in patriotism to an investment to gender norms.

This is textbook white supremicist patriarchial thinking. Shrier's
point is embedded in her irony, but we can still trace her investment
in normativity here, which constellates through patriotism.

THIS READING IS FUN! BUT THIS IS NOT THE KIND OF READING I WANT TO DO.
WHAT I WANT IS TO PULL OUT FROM LEGAL LANGUAGE THE DETAILS THAT
INDICATE SUCH INVESTMENTS. THIS IS THE LANGUAGE THAT CONTROLS US,
RIGHT NOW. THAT IS ATTEMPTING TO CONTROL US RIGHT NOW.

SO I SEE THAT I HAVE TO MOVE SHRIER TO THE TOP!

*** TODO close reading of bills via Butler
The bills are not written irony, they are written in a declarative
legal language. 

Coming back to the bills, we might apply a similar frame 

We can do some similar kind of reading here within a Queer Studies
framework.

#+begin_quote
'The term gender identity means a persons self-perception of their
gender or claimed gender, regardless of the persons biological sex.',

'The term gender means the psychological, behavioral, social, and
cultural aspects of being male or female.',

The term gender transition means the process in which an individual
goes from identifying with and living as a gender that corresponds to
his or her biological sex to identifying with and living as a gender
different from his or her biological sex, and may involve social,
legal, or physical changes.',
 
'The term biological sex means the indication of male or female sex by
reproductive potential or capacity, sex chromosomes, naturally
occurring sex hormones, gonads, or internal or external genitalia
present at birth.',
#+end_quote

In close reading the dataset, I immediately notice how some
assumptions are being constructed in subtle and seemingly neutral
ways. For example, in the first definition, I am interested in the
words "self-perception" and "claimed", and how a view of gender
identity as a subjective experience engages with behavioral dimensions
of gender expression, at least as it has been theorized by Queer
Studies scholars like Judith Butler.

I am also interested in the word “regardless,” which appears in almost
half of the definitions, and suggests a contrast between sex and
gender that seems to reify a binary opposition or between the two. In
other words, gender as being defined without regard to sex, as if
notions of gender and sex do not influence each other, and never blend
into one another, or make productive use of each other. Again I'm
thinking here of Judith Butler, and her famous (and contentious) claim
that even seemingly physical phenomena, like biological sex, is
discursively produced.





While I enjoy doing this kind of analysis of irony, it is exactly the
kind of reading that I don't want to do for this project. Because the
more that I engage with the material and the public discourse around
it, the more I am convinced that this particular historical moment
needs another mode of reading.

** another mode of reading lol


* Footnotes

[fn:1]  The emergence of "Artifical Intelligence" can, in one
trajectory, be traced to Alan Turing's famous essay on the subject
(/Computing Machinery and Intelligence/. Although many people who cite
this origin fail to recognize the Turing made a crucial distinction
between actual intelligence, which is virtually impossible to detect
as experienced subjectively, and the performance of it, which he poses
as the criterion for assessing the quality of machine processing)
which inaugurates what N. Katherine Hayles calls a history of
"information los[ing] its body," as scientific discourses increasingly
overlook the role of the body and embodiment in machine "thinking."
This tendency is to conceptualize thinking or information processing
as separate from the substrate that enables such procedures, bringing
us to where we are today, when casual users of the now ubiquitous chat
interfaces (the contemporary "terminal" of Turing's experiment) find
themselves in thrall to a disembodied subjectivity (There is a
fascinating clash about the role of intention in interpreting machine
generated langauge between computational linguists like Emily Bender,
who assert that intention (specifically, the intuition of intention by
a reader) is necessary for interpretation and Literary Studies
scholars who maintain that intention can be and sometimes is severed
from communicative acts. See "Climbing towards NLU: On Meaning, Form,
and Understanding in the Age of Data", and /Critical Inquiry/'s June
2023 special issue, "Again Theory: A Forum on Language, Meaning, and
Intent in the Time of Stochastic Parrots.").
