* Plausibility and Passing: Using LLMs to Study Anti-Trans Discourse

** outline
- transphobia today
  - what can we learn by studying fear?
  - Sedgwick: studying how fear moves.
  - ROGD will show us WHAT
- deep look into llms, how they are trained
  - they work by approximation, normalization, in a mathematical
    process.
- relationship to Trans Studies and the desire to "pass"
- plausibility and passing

** overview
Research question:
- Is there a way to use the llm training process to study the appeal
  and seduction of transphobia? The way that transphobia /moves/?

** Thank you for having me here today.
SLIDE 1 - TITLE
The title of my talk is "Plausibility and Passing: Using LLMs to Study Anti-Trans Discourse"

In this talk, I'm going to share some of my work customizing large
language models to study bias and discrimination in language.
Specifically, I'm interested in how language can encode bias and
discrimination about sex, gender, and sexuality.

To fine-tune my models, I have been creating custom datasets, which
are based off some of the "anti-trans" legislation in the United
States. For those of you who are not not based in the US or not aware
about this legislation, it limits trans people's rights to things like
healthcare, recognition, and public facilities. 

I will walk you through my own process of creating these datasets and
using them to fine-tune text generation models. I will demonstrate why
language models are apt tools for studying bias in language, which has
to do with the way that the training process transforms language into
a numerical approximation and text generation to a prediction. In what
follows, I will try to surface how some of these aspects of
approximation and prediction in language also relate to theorizing
about sex, gender, and sexuality in Trans Studies.

** transphobia

SLIDE 2 - ANTI-TRANS LEGISLATION TRACKER

First, I'll give a bit of background on the current anti-trans
discourse in the US. As you can see in this chart, there has been a
rising trend of anti-trans legislation over the past several years, in
which our current year has already eclipsed the previous one, though
we are barely halfway through the year. On this chart, you can also
see the different topics for each bill, the most common ones being
healthcare and education. And on the right, a map by Erin Reed, a
journalist closely following the bills, indicates by color where the
bills are most concentrated across the country.

The discourse that drives the bills, and the anti-trans argumentation
and logic, is a kind of transphobia. Underlying a lot of these bills,
especially the ones that ban "gender affirming care" for adolescents,
for example, is a fear of transness as being something contagious.
This fear has actually been formalized into a false syndrome. 

SLIDE 3 - LITTMAN'S PAPER

In 2018, a very controversial paper by Lisa Littman was released,
which coined the term "Rapid Onset Gender Dysphoria," to describe a
condition in which transness can be spread among adolescents in friend
groups and other social settings. The paper recieved numerous
criticisms, involving how it recruited research subjects and failure
to disclose ties to anti-trans publications and groups.

Although the term "Rapid Onset Gender Dysphoria" is not recognized by
any major medical association, and has been denounced by several,
Littman's paper has had a significant influence, sparking numerous
books, shows, and programming around ROGD.

SLIDE 4 - WPATH & CASS

Very recently, in the past few months, two notable reports have been
released which suggest that trans affirmative medical care is harmful
for minors. The first example is the "WPATH files", a supposed expose
of medical malpractice of trans-affirmative care, that targets WPATH,
or the World Professional Association for Transgender Health. Another
is the "Cass Review" in the UK, which was commissioned by the NHS and
recommends limiting medical treatments like puberty blockers and
hormones for teenagers until they become legal adults.

SLIDE 5 - SHRIER BOOK COVER

One notable work, which is in the same vein as these reports, but
directed at a general audience, is a book by Abigail Shrier, called
"Irreversible Damage: The Transgender Craze Seducing Our Daughters."
Shrier's thesis, which becomes more and more explicit as the book
progresses, is that minors do not know what they want, and cannot be
trusted to make what she calls "irreversable" decisions.

SLIDE 6 - FIRST SHRIER QUOTE

Her tone throught the book is ironic and, like so much of transphobia,
seems to seethe with an anger that appears to have no origin. She says
things like: "if the government can’t force students to salute a flag,
the government can’t force a healthcare worker to utter a particular
pronoun. In America, the government can’t make people say things--not
even for the sake of politeness. Not for any reason at all" (xx).
Through the comparison to the flag salute as a kind of enforced
patriotism, the subtext here seems to be that compelling pronoun usage
is fascist. Which is, I think, a strange way to make a point to what
is likely a conservative readership. Unless the point is precisely to
say that some kinds of expression should be free while others should
not.

According to Shrier, even something like social transition, in which a
person changes names, pronouns, and dress, is dangerous and should be
avoided. She writes with a disarming irony about transgender teens'
suicide rates, for example, saying:

SLIDE 7 - SHRIER QUOTE

#+begin_quote
"Of course, the very prospect that their child might self-harm would
bring all but the coldest parents to their knees. If adopting her new
name and pronouns and buying her new opposite-sex clothing is what it
takes to keep her alive, most parents would leap aboard the gender
train... You don’t want your child to hang 'himself' in the garage
just because you accidentally referred to her as 'Rebecca.'” (103-104)
#+end_quote

** what does knowledge do?
Humanists have unique tools for thinking through such discourses based
on fear and repression of sex, gender, and sexuality, particularly in
fields like Gender Studies, Queer Studies, and Trans Studies.

For example, I'm drawn to the work of Eve Kosofsky Sedgwick, who is a
major and influential figure in Queer Studies. 

I'm interested in Sedgwick's work because she offers provocative ways
of thinking through repressive discourses, like those based on fear,
and how they affect expressions of sexuality. Throughout the
trajectory of her career, her reading develops from one that she calls
"paranoid reading,"illustrated in her first book, /Epistemology of
the Closet/).

SLIDE 8 - EPISTEMOLOGY

In this book, she displays a critical practice based on what she calls
Foucault's "logic of repression," that seeks out hidden meaning and
power relations in text, with the ultimate goal of exposure. In this
text, she exposes the unstable binaries between heterosexual and
homosexual categories — where one term is not simply symmetrical or
subordinated to another, but rather, depends the other for its meaning
through “simultaneous subsumption and exclusion” (10).

Years later, Sedgwick's critical method would develop from this kind
of what she calls "paranoid reading" into one called "reparative
reading."

SLIDE 9 - READING

In her famous essay on the topic, "Paranoid Reading and Reparative
Reading: Or, you're so paranoid you probably think this essay is about
you" (pictured right), Sedgwick asserts a central problem about
paranoid reading methods: they do not /motivate/, they do not
/suprise/. Sedgwick explains that this practice, of unveiling or
exposing truth, of revealing the presence of systematic oppression,
injustice, discrimination, is not enough to “enjoin that person to any
specific train of epistemological or narrative consequences” (123). In
other words, exposure does not convince people of anything they don't
already know.

Accordingly, Sedwicks seeks a critical practice that "mov[es] from the
rather fixed question Is a particular piece of knowledge true, and how
can we know? to the further questions: what does knowledge do–the
pursuit of it, the having and exposing of it" (124, Touching Feeling).
She then describes a mode of “reparative reading" that focuses on
connection rather than exposure, in which a reader allows herself to
be taken by surprise.

Sedgwick offers an example. What if, she asks, we take something that
is typically seen as a negative, structuring force in queer identity,
like the feeling of shame, and examine how it unlocks creativity and
productivity?

She explains that,

SLIDE 10: SHAME QUOTES

#+begin_quote
“Shame—living, as it does, on and in the muscles and capillaries of
the face—seems to be uniquely contagious from one person to another."
(63 Touching Feeling).
#+end_quote

Here, Sedgwick takes shame as a contagious affect, to be read as a
mobilizing and creative force in text.

She describes shame as:

#+begin_quote
“not a discrete intrapsychic structure, but a kind of free radical
that (in different people and different cultures) attaches to and
permanently intensifies or alters the meaning of—of almost anything: a
zone of the body, a sensory system, a prohibited or indeed a permitted
behavior, another affect such as anger or arousal, a named identity, a
script for interpreting other people’s behavior toward oneself” (62)
#+end_quote

She demonstrates this reading practice by analyzing metaphors that are
made possible through shame in the fiction of Henry James. Here, she
connects moments of "blushing" and "flushing" to a fantasy of the skin
being entered. Rather than plumb shame's depths for what it reveals
about a hidden sexuality, she uses it to pull other affects and images
into relation. She says, “When we tune into ... language on these
frequencies, it is not as superior, privileged eavesdroppers on a
sexual narrative... rather, it is as an audience offered the privilege
of sharing... exhibitionistic enjoyment and performance of a sexuality
organized around shame” (54).

I'm interested in this move that Sedgwick makes, of taking what is
typically seen as a negative, repressive affect, like shame, and
seeing how it opens up possibilities for reading new connections in
text. Specifically, I wonder one might read something productive in
fear--of the phobias--that pervade the anti-trans discourse. 

** TODO processing and training
Within this discourse, I’m interested in the language outlawing gender
transgression, and how this language encodes a fear of gender
transition, or opting out of binary systems of gender. Why is this
fear so seductive to large part of our population? Why is the fear of
this transgression itself so contagious?

So, from the bills, I decided to create a list of definitions around
gender transgression, defining terms like "gender," "gender identity,"
and "biological sex," for example. I then used that list to fine-tune
an llm for text generation. The idea was that I could then query the
model, asking it questions like "what is sex" and "what is gender".

I anticipated that the results would reveal how bias adheres to
nuances of language, to things like word choice and syntax. I also
anticipated that something about the fine-tuning process itself might
suggest something about reading practices, specifically the way that
we analyze concepts like transphobia from a humanistic perspective.
How might transphobia, as a kind of fear, emerge in text that has
been, so to speak, computationally "generalized" through a massive
statistical process designed to predict the next most plausible word?

In what follows, I'm going to outline a bit of the data gatherering and model training processes.

SLIDE 11 - HUGGINGFACE DATASETS

The first dataset that I created is now available on HuggingFace
Datasets. For those of you who don't know, HuggingFace is a platform
for sharing Machine Learning projects and tools, much like Github.
This dataset consists of definitions of "gender" and related terms
from congressional and senate bills, from the last two years.

SLIDE 12 - DF OF BILLS

To create this dataset, I first downloaded metadata containing bill
titles, ID numbers, and other metadata from the congress.gov website.
Then, using the Python programming language, I wrote a web scraper to
get the plain text of all the bills by their ID. After gathering the
bills, I went through an intensive data preparation process, which
involved cleaning the text and extracting definitions of gender and
related terms from it. I'll highlight some of the major moves from
this process. (And I'll also say here that all of my Python code that
I wrote for this project is publically available, under my github
profile, which I'll link to at the end of this talk).

To extract the definitions of gender terms from these bills, the first
thing I did was to write a pattern matcher, known technically as a
"named entity recognizer" (for those of you familiar with NLP), that
can recognize terms like "gender" and other related terms in text.

SLIDE 13 - NER CODE

Here is a list of labels, organized into the general categories "sex",
"gender", and "sexulaity", with each label specifying a word pattern,
like the phrase "biological sex" for example. I tried to include
various formulations of each term, for example, "transgender" is
delineated three ways, as a single word, as a two-word phrase, and as
a hypthenated word. This ensures that I would capture most if not all
instances of the term

Then, I used that entity recognizer as a basis for a more
sophisticated pattern matcher, which would search for those phrases if
they are contained within a definition.

SLIDE 14 - MATCHER CODE

For those of you familiar with the JSON data format, you can perhaps
grasp the pattern matcher's logic. It starts by searching for
punctuation (specifically, I'm looking for a quotation mark, which
typically surrounds definitions), then looking for a gender term (that
pulls from the entity recognizer), then some wild card terms, just in
case there are extra words or punctuation in the definition. Finally,
I indicate some terms that are common in definitions, like "means",
"signifies", or "includes."

SLIDE 15 - MATCHER RESULTS

Here are some of the initial results from that pattern matcher search.
You can see that the matcher was sensitive enough to capture longer
phrases, like "gender transition surgery means" as well as variants of
how definitions are constructed, using the word "includes" instead of
"means", for example.

After extracting the definitions, I then cleaned them up and formatted
them into a neater list of definitions. The final output then contains
definitions like the following:

SLIDE 16 - DEFS

#+begin_quote
'The term gender identity means a persons self-perception of their
gender or claimed gender, regardless of the persons biological sex.',

'The term gender means the psychological, behavioral, social, and
cultural aspects of being male or female.',

 'The term gender transition means the process in which an individual
 goes from identifying with and living as a gender that corresponds to
 his or her biological sex to identifying with and living as a gender
 different from his or her biological sex, and may involve social,
 legal, or physical changes.',
 
 'The term biological sex means the indication of male or female sex by reproductive potential or capacity, sex chromosomes, naturally occurring sex hormones, gonads, or internal or external genitalia present at birth.',
#+end_quote

I am interested how these assumptions are being constructed in subtle
ways, in seemingly harmless formulations. For example, in the first
definition, I am interested in the words "self-perception" and
"claimed", and how a view of gender identity as a subjective
experience engages with behavioral dimensions of gender expression, at
least as it has been theorized by Queer Studies scholars like Judith
Butler. I am also interested in the word “regardless,” which appears
often, in about half of the definitions, and suggests a contrast
between sex and gender that seems to reify a binary opposition or
between the two. In other words, gender as being defined without
regard to sex, as if notions of gender and sex do not influence each
other, and never blend into one another, or make productive use of
each other. Again I'm thinking here of Judith Butler, and her famous
(and contentious) claim that even biological sex is a discursive
phenomenon.

As I continue to build and clean my datasets, I've also been dabbling
with using them to train AI models.

As you may already know, an AI model "learns" what words mean based on
context. From its training data, it compile numerical probabilities
for each word relationship to other words in the database. It
represents these probabilities with numbers, with actually a very
large list of numbers, known technically as "word vectors."

To us, these scores look just like a long list of numbers, but to a
computer, the scores represent a given word's meaning through its
relationship to every other word in the entire dataset of words. A
language model will generate content by doing math with the scores
attached to each word in its database. And the math that they use to
make generate text is math that many of us have heard of before in
high school math: things like matrix multiplication and cosine
similarity.

SLIDE 17 - VECTORS

And here's a famous example of a very simple formula. In this formula,
the idea is that by taking all the numbers that represent king, then
subtracting the ones that represent man, and adding the ones that
represent woman, you will get queen. I won't get into the sexism of
this formula--what exactly is being subtracted from King, for example?
is it a biological object, a social behavior?

But I want to point out how statistical prediction pervades the whole
process. And prediction opens a connection between Machine Learning
and Trans Studies concepts. To demonstrate this connection, I'm going
to go into a bit of detail behind the training process for these
tools, explaining some of the mathematical operations.

To create these word vectors, there are three steps, each representing
an important mathematical function.

SLIDE 18 - LIST OF FUNCTIONS

1. first, the hypothesis function
2. second, the loss function
3. third, the minimizing loss function

First, because the machine doesn't know what words mean, it has to
"guess." (This is called the hypothesis function), Here, it populates
each word with a vector, consisting of random numbers. It's a starting
point. These random numbers will determine what word it chooses to
follow any given word.

After making this guess, it moves to the next step. Here, the machine
will check its prediction against the actual result. It's prediction
will be wrong, but that doesn't matter. It compares between the two,
the prediction and the result, and calculates the difference between
them. This calculation is made by using what's called the "loss
function."

Finally, it moves to the minimizing this "loss", which employs
algorithms from calculus (like gradient descent) in order to /very
slightly/ minimize the loss. In other words, it adjusts the original
prediction so that it is slightly closer to the intended result. The
adjustments here are very small, incremental. Because it doesn't know
the correct answer, it makes a huge number of guesses. This may seem
inefficient, but with enough guesses, it can actually adjust the
numbers until there is /almost zero difference/ between our prediction
and the actual result.

** plausibility 
These models, as you can see, generate text by approximating what it
means. It is a kind of normalization of language, which turns semantic
expressivity into something that can be computed and predicted.

With enough training data, LLMs can be really good generating content
that is plausible. However, while they can guess or improvise, they
are not at all good at being creative, at innovating. A language model
can only generate what it has already seen before. Even a phenomenon
like “hallucination,” that a language model spews text that has no
bearing in reality, is based on the tendency of models to repeat what
they've already seen. They hallucinate not because they are creative
or random, but because they are designed from statistical processes to
generate what is most plausible rather than accurate.

This tendency toward plausibility creates an interesting perspective
for me to think through how Trans Studies scholars have characterized
trans affects. Typically, these scholars describe trans affective
modes by distinguishing them from "queer" modes. For example, Trans
Studies scholar Eliza Steinbock explains that,

SLIDE 19 - TRANS AFFECTS

#+begin_quote
“trans analytics have (historically, though not universally) a
different set of primary affects than queer theory. Both typically
take pain as a reference point, but then their affective interest
zags. Queer relishes the joy of subversion. Trans trades in quotidian
boredom. Queer has a celebratory tone. Trans speaks in sober detail.
Perhaps the style of trans studies has been for the most part realist,
but this should not be mistaken for base materialism. Even speculative
thinking requires enough detail to launch into new realms.”
#+end_quote

Other Trans Studies scholars like Marquis Bey and Andrea Long Chu have
made similar points; with Bey making the point that queer's
intervention can be described as "anti" or militant, while trans is
"non" or based in refusal ("Thinking with Trans Now"); and Chu has
remarked that trans studies, rather than resisting norms, "requires
that we understand–as we never have before–what it means to be
attached to a norm, by desire, by habit, by survival" ("After Trans
Studies" 108).

It seems to me--there is a fascinating connection between how language
models approach language, what they do to language (the normalization
or approximation) of language, and what Trans Studies scholars defines
as a central desire to pass.

This makes me wonder, could AI-generated text, as a kind of
approximation, a normalization, of its training data, be used to study
the attachments to norms and the quotidian that characterizes--not
trans affective modes--but those based on fear of transness? Could
these same processes be used to study the attachment to norms that
characterizes transphobia, like perspectives driven by the fear of
ROGD? What might outputs from AI text generation suggest about the
allure, the threat, the “seduction,” as Trans Studies scholar Cassius
Adair puts it, of gender transgression?

While this project might sound very ambitious, I'll admit that, so
far, model training is still in progress. I need to continue to tweak
my model configuration, probably numerous times.

SLIDE 20 - RESULTS

Nonetheless, here are some excerpts of my language generated by my
model so far.

As you can see from skimming the results, the models are showcasing
the tendency toward plausibility, specifically in the tendency to
repeat itself, which is its own fascinating area of study in machine
learning research.

I will close now by coming back to this idea of fear, and particularly
the fear of contagion, which drives some strains of transphobia.
Cassius Adair offers a useful perspective for thinking through the
fear of contagion. In his study of trans erotics, and specifically
“trans for trans” or "t4t erotics," Adair asks, "Why shouldn't
transness be transmissible or contagious? Why can't the erotic be a
site of producing trans identity or practices?" He points out that,
after all, cis people do it all the time: they use sexuality and
sexual encounters as sites of identity formation.

Here, I see Adair doing for contagion what Sedgwick does for shame:
turning something that is traditionally seen as a negative into
something that may be generative and productive.

This is a kind of reading that allows one to take what has been a tool
of oppression and turn it into a creative resource. Sedgwick explains
that this kind of reading exposes “the ways selves and communities
succeed in extracting sustenance from the objects of a culture—even of
a culture whose avowed desire has often been not to sustain them”
(Touching Feeling 151).

SLIDE 21 - THANKS AND CONTACT

For those of you who want to follow this work, you can find me on
Github and HuggingFace under the username, Gofilipa. 

Thank you.




