* Plausibility and Passing: Using Ai To Study Anti-Trans Legislation
** notes from DJAI
[[~/Desktop/anti-trans-legislation/talks/design_justice/design.org][link to djai paper]]

Possiblity for tracing the language in the bills to an origin point?
To special interest groups that are providing the language? 
(Pamela)

On reading, "emerging textual practices":
- What is the state of the text when you're doing this analysis?
  (Kath) Does that matter?
- Differentiate between the different kinds of reading across
  different stages of the text. (Lauren)
- "as you put it in your question – what is being subtracted from
  ‘man’ – is this gender bias or discrimination or something
  different? What do we gain or lose by understanding these emerging
  textual practices through existing paradigms for understanding the
  sociomaterial production of difference?" (Kath)

On bias (from Kath):
- "Is it ever possible to remove bias? What is bias if it can be
  removed or added? Why are humans better able to ‘detect’ bias than
  nonhumans? Bias in the context of something that is removable
  suggests a single world in which things can be represented like or
  unlike what they are really, which seems to be a set of assumptions
  that queer theory and design justice have usefully undermined."
  (Kath)
- "if these textual formations are problematic, are there any that are
  not- or unproblematic? It seems to me from your presentation that
  you were exploring the indeterminate morality of textual-affective
  practices, but are these only possible – or perhaps only productive
  – when done in ‘literary’ or ‘human’ ways? I think the complexity of
  what it means for some practices to be a problem is what you’re
  raising when you say that it’s not what these LLMs/word embeddings
  are but what is done with them that is fraught… i.e. that they are
  enacted as if they are simply showing what is already there. But if
  that’s the case then that also challenges the idea of LLMs mirroring
  bias/discrimination in their datasets." (Kath)

What about using the dataset and applying it to just studying word
embeddings, creating a language model to query embeddings, or to look
at wordnet. Maybe trying to create a kind of foruma like hormones +
contagion = trans or something. (Kath)

Distinguish between transphobia and ant-material transness. There are
different kinds of attacks across different spaces (Funmi)

See Abiba Berhani and Discriminating Data.

My thoughts: 
The idea is not to remove bias, but to use the machine and statistical
processes to better understand the forms that bias takes in language.

** plans
I think I want to....

- run more experiments
  - get the data I need from the PDFs of state bills
  - train a word embedding model
  - keep working on tweaking parameters for the congressional dataset
  - start creating new datasets for the new congressional bills

Two interventions:
- ways of reading; determine a reading method, approach:
  - /how to read transphobia in legislative text/, in a way that
    doesn't just reveal transphobia, but does something else.
    - the problem, for me, is that these definitions/texts reflect
      just a massive bias that already exists in the United States.
      And there's no way of my reading it that's going to change
      anything. So what do we do in the face of it?
      - This question, of what we are reading for, and how, and why,
        is the motivating one for this chapter.
      - Is there something in particular about gender and gender
        transition that we can understand here? 
    - reading along the method/tool:
      - we try to read for the mechanism, looking into the mechanical
        workings of the tool as a clue. What does it do to data, to
        forms? How does this mechanism offer a clue, a suggestion, for
        reading?
      - looking at the "plausibility" of output text, of how models
        work to normalize and regularize, to find the most
        statistically plausible next word.
        - how this drive toward plausibility mirrors the "desire to
          pass" that trans studies scholars have read in trans
          subjects. A desire for conformity, for convention.
	- there are people who want to explode gender, and people who
          simply want to pass.
	- is there something about the regularization of language
          which we can then apply back to understand gender?
      - what do we see in the language of the output text, which has
        been regularized, what is on the surface of that language,
        what connections are opened?
  - attachment to normativity; the plausibility of machine learning
    outputs.
    - /Could the trans investment in normativity be a critical optic
      for examining far right investments?/
- solidify my approach wrt trans studies
  - interest in contagion, connection to sexuality, desire, and fear.
    How to constellate all of these ideas.
    - transphobia: the fear that being trans can spread like a
      contagion. This is a popular fear, which engages in some way
      with the legislative language. 
    - contagion as seduction --> a means of identity formation.
      - conversation of seduction is based on the loss of agency (as
        if we have control over our actions anyway). What if we
        focused on seduction as a means of identity-formation?
	- as a kind of subject-less subjectivity? (See Marquis Bey,
          "After Trans Studies"), which would enable us to make new
          kinds of coalitions?
      - in seduction there is a giving up of choice, of agency. It is
        a decision made through arousal. You do something that maybe
        you wouldn't have done if not aroused. (this is what I am
        talking about in my previous chapter... how the fuck am I just
        realizing it now). 

On reading trans studies:
- My interest in Trans Studies, and transphobia, is in dialogue with
  misinformation studies. That's part of the dimension of transphobia
  that I'm interested in.
- Some think Trans ought to focus on attachment to normativity, while
  others on resistance and radicality:
  - Chu and Drager: the focus in trans studies has been on resistance
    and radicality, when trans people just want to conform. It borrows
    too much from Queer Studies and cannot distinguish itself. 
    - all attempts to conform are nonnormative, even heterosexual
      ones, because "normativity is impossible"
  - Halberstam:
    - trans and queer blend and blur into each other--this is useful.
      They have the same target: normativity.
      - "if we are all females, then there are notranssexuals, no
        queers, no men. In the future, may I suggest, we who are
        queer, ortrans, or feminist might remain focused on a more
        conventional enemy: namely,the beneficiaries of
        hetero-patriarchal systems who, far from being females and
        hating it, are deeply invested in being males and loving it"
        (329).
      - Debates between "real vs performativity" by Prosser, Butler,
        and Halberstam (2005).
      - Debates on "cross-identification" and "cross-gender
        identification" by Bey and Manalansan. 
    - Chu's version of "female" posits femininity as lack, which is
      lacanian, second wave feminist, and an idea that Butler has done
      away with in "The Lesbian Phallus". See Kay Gabriel's LARB
      review (2019). 
- Jay Prosser vs Butler: get this right!

** outline // 
- close-reading the bills:
  - bill titles show protective, traditional investments
- trans as contagion
  - ROGD, Lisa Littman.
  - quote from Shrier - pulling out the contradictions and subtle
    meaning - the kind of reading that I don't want to do.
    - looking for a new reading method. Of bringing some things to the
      surface (yes a practice of revelation) but of bringing things
      into relation in a new way.
- sedgwick's paranoid vs reparative reading: how can critique /move/?
  - what sedgwick does for shame, I'd like to do for contagion, fear.
  - like sedgwick, looking for a way of reading that doesn't simply
    unearth oppression, but looks for something else, something
    different, some kind of relation
    - conversations in trans studies about attachment to normativity
      as distinguishing trans from queer.
    - what if we could use transphobia as a vehicle about learning
      about this attachment to normativity? And attachment that
      animates the bills?
      - what kind of reading would this offer?
- turning to AI, statistical methods, to explore the language of transphobia
  - "fine-tuned" a language model off gender and related terms from
    the bills.
  - entity recognizer and pattern matcher to capture the data
  - hypothesis, loss, minimizing loss
- prediction --> plausibility
  - the iterative shifting of vectors is a kind of approximation, or
    normalization of language, a tendency toward plausibility.
    - each step of the process, each iteration, gets closer and closer
      to a kind of mean, average, for that word's "meaning" in the
      data.
  - connection to trans studies affective modes as distinguished from
    queer ones:
    - attached to a norm rather than resisting norms
    - the desire to pass
  - could AI processes, as a kind of normalization of training data,
    be used to study the attachments to norms and the quotidian that
    characterizes--not trans affective modes--but those based on fear
    of transness?
    - AI is an apt tool to study the attachment to norms that
      characterizes transphobia, like ROGD. What might outputs from AI
      text generation suggest about the allure, the threat, the
      “seduction,” as Trans Studies scholar Cassius Adair puts it, of
      gender transgression?
  - Adair: contagion and seduction being a site of identity formation.
    Straight people do it all the time, using sex and sexuality as
    sites of identity formation.
    - Adair does for contagion what Sedgwick does for shame: turns
      something negative into a creative resource.

*** bank
  - gender as a subjective phenomenon, "claimed" "self-perception"
  - word "regardless" to distinguish gender from sex, seems to make
      them independent but actually reifies a binary opposition
      (Butler's subordinated realm).

** draft
*** thank you for having me
Thank you so much for having me here. 

I'm going to talk about a project that I've been working on for a
little over a year, which takes as its subject transphobia, and
particularly anti-trans discourse, which is currently proliferating
across this country.

To study this subject, I'm using machine learning as my methodology.

I'm interested in how machine learning processes, in how predictive
algorithms, which reconfigure and reproduce the data that they are
trained with, can be used to study human bias, preconceptions,
contained within that same data. For this project, I train a machine
learning model off of data from current anti-trans legislation, which
is, legislation currently being proposed, debated, and passed all over
the country, which limits trans peoples' rights, legal recognition,
and access to healthcare. 

For this presentation, I'm going to focus on methodology.

First, I'm going to talk a little bit about readings methods, and
specifically, about ways of reading transphobia that engages existing
critical discourses in trans studies.

Then I'm going to turn to machine learning, and my attempts to use it
to explore the language of transphobia. Here I will get a little bit
technical, going "under the hood" of the machine, as it were, to
surface the underlying processes that constitute so called "deep
learning" methods.

Finally, I'll bring these two areas--trans studies and machine
learning--together. I will show how these two areas can
cross-illuminate one another. I will propose a reading practice that
uses "predictability" in machine learning to study transphobic
language, and in particular, how this language exhibits attachment to
normativity, what I call "plausibility."

(and what do I want from you? feedback on what you make of this
reading process, I guess?). 

*** legislation, transphobia, ROGD, littman
So I begin with my subject matter -- transphobia. This project looks
at transphobia within a legal discourse. As I'm sure you're aware, the
past 3 or 4 years has seen an incredible jump in the number of bills
being proposed and passed in state houses across the country and in
congress.

[SLIDE - ANTI TRANS LEGISLATION TRACKER - NEEDS NEW IMAGES]

As you can see in this chart, there has been a rising trend of
anti-trans legislation over the past several years, where each year
eclipses the previous one. The majority of these bills target
education, seeking to ban gender identity education, and students'
chosen names and pronouns, as well as healthcare, where many bills
outlaw gender-affirming care for minors and adults. The rest of the
bills mainly focus on trans peoples' participation in public spaces
and events, like drag performances and bathrooms, and also in sports.

[SLIDE - FEDERAL BILL NAMES]

- US HB1064: Ensuring Military Readiness Act of 2023
  - disqualifies transgender persons from military service
- US HB1276: Protect Minors from Medical Malpractice Act of 2023
  - doctors to be liable to all adverse effects (physical,
    psychological, etc) following trans-affirming care
- US HB1399: Protect Children’s Innocence Act
  - gender-affirming care on minors to be a felony
- US HB1490: Preventing Violence Against Female Inmates Act of 2023
  - incarcerating people by "biological sex"
- US HB216: My Child, My Choice Act of 2023
  - schools to obtain written parental consent before teaching
    anything related to gender/sex/sexuality.
- US HB3101: TPA Act Traditional Passport Act
  - passport gender designation to be binary and based on sex
- US HB3102: TSA Act Traditional Screening Application Act
  - prohibits "X" gender designation on TSA screenings

And here, you'll see a list of bill titles, like "Ensuring Military
Readiness Act," and "Protect Children's Innocence Act," which are
currently being debated in Congress. Just by scanning the titles, you
can perhaps grasp how many of these bills are undergirded by similar
assumptions, like that Americans need to be protected from gender
nonconformity. According to these bills, the groups most in need of
protection from trans people and trangender ideologies are minors, who
are "innocent", and cis women, who are physically vulnerable to
"violence". Alongside this investment in protection, is another
investment in maintaining tradition. We see "traditional passport,"
which preserves the binary gender identifications on passports, and
"traditional TSA," which keeps the binary gender designation on
security screeners (which is kind of hilarious, as I don't know
anybody that thinks TSA is a tradition that needs to be protected).
What I'm trying to surface here, is that underlying these bills, is an
attachment to the idea that transness, whatever else it might do,
constitutes a threat to American people and way of life.

The discourse that drives logic of threat and protection is a
particular kind of transphobia based on contagion. As particulurly
evident in the bills that limit or ban "gender affirming care" for
minors, this fear is propped by the assumption that transness can
spread from person to person, that it is a kind of social contagion.

SLIDE - LITTMAN'S PAPER

The fear is formalized in the false medical diagnosis, "Rapid-onset
Gender Dysphoria," or ROGD. This diagnosis, which has been rejected
and renounced by medical associations, was nonetheless popularized in
2018, in a very controversial paper by Lisa Littman. For that study,
Littman enlisted participants (parents of transgender adolescents)
from conservative and anti-trans online forums. Despite receiving
numerous criticisms for its methodology and lack of disclosures, the
paper has nonetheless had a significant influence on public perception
around Trans issues, especially as they affect minors. The idea has
seeped into public discourse, appearing in books, podcasts, and news
reports, and across social media.  

SLIDE - SHRIER BOOK COVER

One notable work in this vein, which is directed at a general
audience, is a book by Abigail Shrier, called "Irreversible Damage:
The Transgender Craze Seducing Our Daughters." Shrier's thesis, which
becomes more and more explicit as the book progresses, is that minors,
who do not know what they want, cannot be trusted to make what she
calls "irreversable" decisions. According to Shrier, even something
like social transition, in which a person changes names, pronouns, and
dress, is dangerous.

I'm going to talk about her language. Unlike the language of the
bills, Shrier's tone throughout the book is highly ironic, an irony
that embeds interesting subtexts. 

SLIDE - SHRIER QUOTE

For example, there is a double meaning behind some of her
pronouncements, which is decipherable by her ironic tone.

She says things like: "if the government can’t force students to
salute a flag, the government can’t force a healthcare worker to utter
a particular pronoun. In America, the government can’t make people say
things--not even for the sake of politeness. Not for any reason at
all" (xx).

Here, Shrier makes a comparison to patriotism--in the flag salute--to
make a point about governmental authority. The point is that the
government cannot compel its citizenry (or anybody within its
jurisdiction) to express loyalty to the country's symbols. And just as
the country cannot compel patriotic expression, so it cannot compel
respect (or here, she refers to it as "politeness") for a person's
preferred gender designation.

Through this comparision to the patriotism, and the framing of the
issue around expression, the subtext here seems to be that forcing
pronoun usage would be fascist. Which is, I think, a strange way to
make a point to what is likely a readership that I imagine is highly
invested in conservative ideals.

Unless, reading this statement through the frame of irony, the point
is precisely that some kinds of expression should be free while others
should not. That we have the right to question each other's genders
but not, but never, the flag. Essentially, if citizens cannot be
compelled to address such a providential institution according to
their personal feelings, then of course, they have the right to
address an individual how they like. Unironically, the sentence could
be saying something like, "look, our government cannot even force you
to respect it. How admirable, how humble, that a nation would endow
its own citizens with the right to disrespect it! Anybody who does so,
is undeniably selfish."

In this reading, we can trace an attachment to patriotism to an
attachment to gender norms (perhaps with a stop at white supremacy on
the way there). And we can see how the structure, what Patricia Hill
Collins calls "the matrix of domination," works.

But this is exactly the kind of reading that I don't want to do for
this project. Because the more that I engage with the material, the
more that I listen to the news of another trans bill being proposed in
this country, the more I am convinced that this particular historical
moment, a moment of multiplying misinformation, needs another mode of
reading.

*** sedgwick, paranoia, shame, movement
Here I am inspired by the origins of my own field, which is Queer
Studies. As many of you know, one of the major figures of this field
is Eve Kosofsky Sedgwick, who, throughout the trajectory of her career
explored various reading methods and modes of relation to text.

SLIDE - EPISTEMOLOGY

In her early work, such as /The Epistemology of the Closet/, Sedwick
practices a mode of critical analysis based on what Foucault's "logic
of repression," that seeks out hidden meanings and power relations in
text. In this book, she exposes the unstable binaries between
heterosexual and homosexual categories — where one term is not simply
symmetrical or subordinated to another, but rather, depends the other
for its meaning through "simultaneous subsumption and exclusion" (10).
In what she calls the "epistemology of the closet," this method mines
language forms for what is hidden, what is obscured, and what this
closet reveals about power relations and structures.

SLIDE - sedgwick paranoid/reparative essay

Years later, however, Sedgwick changes course. In the wake of the AIDS
crisis, she experiences an upheaval of doubt about the efficacy of
critical methods which she famous calls "paranoid reading." This doubt
catalyzes her argument in what is perhaps her most well-known essay,
"Paranoid Reading and Reparative Reading: Or, you're so paranoid you
probably think this essay is about you" (such a great title). In this
essay, Sedgwick questions the role of exposure in critical inquiry.
She wonders what any explanation, any proof, for example, of the
government's neglect for African American lives and gay lives
decimated by the AIDS pandemic, would achieve. She opines that
revealing truth, on its own, does not /move/ people to any particular
action or conclusion. She explains that "for someone to have an
unmystified, angry view of large and genuinely systemic oppressions
does not intrinsically or necessarily enjoin on that persons to any
specific train of epistemological or narrative consequences" (123).

What if, she asks, we consider ways of knowing not oriented around
suspicion and paranoia? This would be a critical practice that
"mov[es] from the rather fixed question Is a particular piece of
knowledge true, and how can we know? to the further questions: what
does knowledge do–-the pursuit of it, the having and exposing of it"
(124, Touching Feeling).

To demonstrate, Sedgwick takes an affect that is traditionally seen as
negative, and examines how it creates productive and generative
effects in text. She takes shame, which is a structuring force in
queer identity, and explores its significatory possibilites. She
describes shame as:

SLIDE - SHAME QUOTES

#+begin_quote
“a kind of free radical that (in different people and different
cultures) attaches to and permanently intensifies or alters the
meaning of—-of almost anything: a zone of the body, a sensory system,
a prohibited or indeed a permitted behavior, another affect such as
anger or arousal, a named identity, a script for interpreting other
people’s behavior toward oneself” (62)
#+end_quote

Rather than, as much Queer Theory is happy to do, plumb and trace the
ways that shame hides and represses sexuality, Sedgwick reads it as a
vehicle for connection, pulling other affects and images into
relation.

She even likens shame to a kind of contagion, bringing out the ways it
can spread from person to person, evoking its ability to mobilize and
generate:

#+begin_quote
“Shame—-living, as it does, on and in the muscles and capillaries of
the face—-seems to be uniquely contagious from one person to another."
(63 Touching Feeling).
#+end_quote

I'm interested in this move that Sedgwick makes, of taking what is
typically seen as a negative, repressive affect, and seeing how we
might read it differently. Specifically, I wonder how one might read
something productive in fear--in the phobia--that pervades anti-trans
discourse.

I'm interested particularly in the way that transphobia mobilizes as
an anxiety or desire for normativity. And the reason has to do with
one conversation being had the field of trans studies, which considers
the role of trans studies with regard to queer studies, and how the
two fields, in pursuing distinct projects, could be associated with a
different set of core affects. 

For example, trans studies scholar Eliza Steinbock explains that,

SLIDE 16 - TRANS AFFECTS

#+begin_quote
“trans analytics have (historically, though not universally) a
different set of primary affects than queer theory. Both typically
take pain as a reference point, but then their affective interest
zags. Queer relishes the joy of subversion. Trans trades in quotidian
boredom. Queer has a celebratory tone. Trans speaks in sober detail.”
#+end_quote

Other Trans Studies scholars like Marquis Bey and Andrea Long Chu have
made similar points; with Bey making the point that queer's
intervention can be described as "anti" or militant, while trans is
"non" or based in refusal ("Thinking with Trans Now"); and Chu has
remarked that trans studies, rather than resisting norms, "requires
that we understand–-as we never have before–-what it means to be
attached to a norm, by desire, by habit, by survival" ("After Trans
Studies" 108).

You'll remember in the list of bill titles from before, that I read an
underlying fear of trans as contagion. That transness-as-contagious
represents a threat to the American way of life.

However, in all the patriarchal language of the bill titles, in words
like "protect," "preserve" and "ensure," and the fear of change that
they imply, there is also some kind of attachment, to normativity, to
maintaining tradition.

I wonder if we might, instead of focusing on what fear is afraid of,
that is, on gender nonconformity, to instead read the positive
attachments implied by fear, what fear signifies about desire and
attachment. I wonder how reading specifically for a desire for
normativity might what it evoke.

/A question under the surface: What might far-right investment, we can
call them radical conservatist investments, in normativity reveal
about trans investments in normativity?/

Now, in the next section, I'm going to explain why I think that
machine learning is a particularly good method for this task of
studying normativity. 

*** processing and training
Now I will talk a little bit about the technical process behind the
machine learning portion of my project. This process involves data
gathering (that is, taking and processing text from the legislation),
and model training (which is, using my prepared dataset to train a
machine learning model so that it can predict results based on my
dataset). 

I'm going to go a bit into technical detail here, because the
mechanism of the technology is important to my thinking through
method. That being said, I will try to be as clear as possible so that
people with no technical or machine learning background (which I
assume is most or all of you!) can follow along with the process. 

*** prediction
So, to put it most succinctly, the thing that interests me the most
about machine learning is the way it works on prediction. As many of
you may know, all machine learning models (like the one that runs the
main "engine" of ChatGPT, for example), make predictions, or guesses,
as to what word should follow another word.

In order to make these predictions, models need to be "trained". That
is, they need to first "read" text, actually massive amounts of text.
Once they have processed enough text, they have a sense of language
patterns, of how sentences generally are formed, and also of context,
of what words tend to appear in similar contexts. Just from reading
text, they can get a sense of syntax, grammar, and even topic.

Now, I should point out here that you cannot look inside of a model to
see how it understands language. If you were to peak inside of a model
(and at the end, I'm going to give you a little peak), all you would
see are individual words followed by massive lists of numbers. And
I'll explain what that means in due time. For now, I just want to
assert that the model doesn't have any kind of conceptual knowledge of
these things, it doesn't understand the concept of "syntax," per se,
but only what words tend to surround the word "syntax." More on that
very soon.

*** data processing
So, now that we know these models function by prediction, we can talk
about how they are trained to make those predictions. They are trained
off data, that is, off of text. Models will go through many rounds of
training in order to be optimized for specific tasks.

The first round of training is called "base model training". And this
training is really only possible if you have access to many thousands
of dollars (often millions of dollars) worth of computer hardware,
energy, and labor. That kind of training is really only available to
big tech companies like Google, META, Amazon, Microsoft, which as you
know, all have their own competing models.

But after the base model is trained, then the model goes through
rounds of fine-tuning, which involves much shorter training runs on
much smaller datasets. This is a kind of training that's more
accessible, and someone with consumer hardware (and a little bit of
technical know-how) can do it on their own. This is the kind of
training that I decided to use to explore transphobia in the
legislative bills.

So, I needed first to create a dataset for training. I decided to
create a list of definitions around gender, with definitions of terms
like "gender identity," and "biological sex," for example. I then used
that list to fine-tune a model. The idea was that I could then query
the model, asking it questions like "what is sex" and "what is
gender," and see how it would respond. 

To create this dataset, I went through an intensive data preparation
process, which involved using the Python programming langauge to
scrape the legislative bill text and then extract definitions of
gender and related terms from it. I'll highlight some of the major
moves from this process.

(And I'll also say here that all of my Python code that I wrote for
this project is publically available, under my github profile, which
I'll link to at the end of this talk).

To extract the definitions of gender terms from these bills, the first
thing I did was to write a pattern matcher that can recognize terms
like "gender" and other related terms in text.

SLIDE - NER CODE

Here is a list of labels, which are the terms that are completely
capitalized, organized into the general categories "sex", "gender",
and "sexuality", with each label specifying a word pattern, like the
phrase "biological sex" for example. I tried to include various
formulations of each term. For example, "transgender" is delineated
three ways, as a single word, as a two-word phrase, and as a
hypthenated word. This ensures that I would capture most if not all
instances of the term.

Then, I used that pattern matcher as a basis for a more sophisticated
pattern matcher, which would search for those phrases if they are
contained within a particular sentence structure, like if they were
the subject of the sentence, followed by verbs like "means" or
"signifies" or "includes", or something related. I would show you that
code too, but it's going to look very confusing, and I think it will
create more problems than clarity.

SLIDE - MATCHER RESULTS

Her are the results from running the pattern matcher on the bill text.
Here, you can see that this matcher was sensitive enough to capture
longer phrases, like "gender transition surgery means" as well as
variants of how definitions are constructed, using the word "includes"
instead of "means", for example.

And here's some examples of the results after some cleaning and
formatting. I'll read a couple of them out loud.

SLIDE - DEFS

#+begin_quote
'The term gender identity means a persons self-perception of their
gender or claimed gender, regardless of the persons biological sex.',

'The term gender means the psychological, behavioral, social, and
cultural aspects of being male or female.',

'The term gender transition means the process in which an individual
goes from identifying with and living as a gender that corresponds to
his or her biological sex to identifying with and living as a gender
different from his or her biological sex, and may involve social,
legal, or physical changes.',
 
'The term biological sex means the indication of male or female sex by
reproductive potential or capacity, sex chromosomes, naturally
occurring sex hormones, gonads, or internal or external genitalia
present at birth.',
#+end_quote

In close reading this dataset, I am tempted to make the following
observations about how these definitions imply subtle but telling
assumptions about gender.

For example, I am interested in the word “regardless,” which appears
in many of the definitions, and along with the comma that precedes,
it, seems to partition gender from sex in the defintions. This
partition suggests a contrast between sex and gender that reifies
their binary opposition. Gender here is being defined without regard
to sex, as if notions of gender and sex do not influence each other,
and never blend into one another, or make productive use of each
other. Again I'm thinking here of Judith Butler, and her famous (and
contentious) claim that even seemingly physical phenomena, like
biological sex, is discursively produced.

In other definitions, I am interested in the words "self-perception"
and "claimed", and how a view of gender identity as a subjective
experience engages with behavioral or outward-expressing dimensions of
gender expression, which is another idea that has been addressed in
Queer Theory.

But this is not the kind of reading that I want to do with this
project. This kind of reading looks for what the definitions might
reveal about certain ideas about gender, sex, or sexuality. It is a
kind of paranoid reading, which looks for an underlying system of
oppression. Rather, I'm interested in what these definitions might
open up in our understanding of normativity, and the attachment to
normativity. 

*** training process
So, let's come back to this concept of prediction, and look at what
actually happens to language when a model is being trained.

As I mentioned before, machine learning models learn to generate text
based on what they've seen before in their training data. But how does
that process actually work, in technical terms?

Basically, the answer has to do with math. Machine learning turns
language, that is, semantic expressivity, into something that can be
computed and guessed with math.

A model will assign each word a definition, which is, actually,
a list of numbers. Each number in that list of numbers represents its
relation to another word in the dataset, it is a probability for that
relation between two words.

Once a model has a list of numbers to represent each word, it can then
use algorithms (mostly from calculus) to calculate which words should
be put together, side by side, in a sentence. So text generation is
really just turning language, semantics, into something that can be
computed in numeric form. If a word can be represented by a list of
numbers, then we can use that list of numbers to do some math to
figure out where that word ought to go in a sentence. (for those of
you who want to learn more about this fascinating phenomenon, look up
the phrase "word vectors", which is the technical term for this
concept). 

So, words are represented by numbers, and models do calculus to figure
out which word goes where. But how does it know what numbers to assign
to certain words? How does it generate these lists of numbers in the
first place?

It generates them by a very complex training process. This training
process can be roughly reduced to three stages, or steps. Each step
contains a mathematical function, which is really a very long and
complicated formula. So you can get a high-level sense of what's
happening, I'm gloss over each step briefly.

When a model is being trained, it is 

*** TODO SLIDE - LIST OF FUNCTIONS

1. first, the hypothesis function
2. second, the loss function
3. third, the minimizing loss function

The first function is called the "hypothesis function." Here, a model
will take a sample sentence from the dataset, and it will block out
the second half of that sentence. Then, it will try to guess which
words should go in that second half. Because the model has no idea
what the words mean, the guess will be wrong. But that's doesn't
matter, because the purpose of the hypothesis is to make any guess, so
that it has something from which it build on in the future steps. The
numbers here are just a starting point.

Then, after making this guess, it moves to the next step, where the
machine checks its prediction against the actual result--that is, it
will compare the predicted word against the actual word (and remember
that, all words are represented by numbers, long lists of numbers).
Because the words are represented by numbers, it can calculate the
mathematical difference between the prediction and the actual result.
This calculation is made by applying what's called the "loss
function." And the "loss" here is a numerical representation of this
difference between prediction and actual result.

Finally, in the third step, it moves to the minimizing this "loss",
which employs algorithms to /very slightly/ adjust the lists of
numbers (attached to each word) so that they are closer to the
intended result. The adjustments here are very incremental. But with
enough of them, the model can reach /almost zero difference/ between
the prediction and the actual result.

With enough training data, language models can be really good
generating content that is plausible. However, while they can guess or
improvise, they are not at all good at being creative, at innovating.
A model can only generate what it has already seen before. Even a
phenomenon like “hallucination,” that a model spews text that has no
bearing in reality, is based on the tendency of models to repeat what
they've already seen. They hallucinate not because they are creative
or random, but because they are designed from statistical processes to
generate what is most plausible rather than accurate.

Although I am still working on the right configurations for my
training, I do have some initial examples of how it is defining some
gender related terms.

SLIDE - MODEL GENERATION RESULTS

In these examples, the model is defining the terms "transgender" and
"gender affirmation".

As you can immediately notice from skimming the results, my model
displays a tendency to repeat itself, which is tendency of generating
not what is most expressive, but what is most plausible.

*** plausibility
Thinking back to this training process, I read this iterative shifting
of numbers (representing words) within the model as a kind of
/approximation/ or even /normalization/ of language. The model
generates language by approximating what is most likely, most
plausible, based on its training data. 

Here, I see a fascinating connection between how language models
approach language, what they do to language (the normalization or
approximation) of language, and what Trans Studies scholars defines as
an attachment to normativity, that is, a desire to /pass/.

This makes me wonder, could generated text, as a kind of
approximation, a normalization, of its training data, be used to study
the attachments to norms and the quotidian that characterizes--not
trans affective modes--but those based on fear of transness?

Thinking in this way, machine learning may be an apt tool to study the
attachment to norms that characterizes transphobia, like perspectives
driven by the fear of Rapid-onset Gender Dysphoria. What might outputs
from text generation suggest about the allure, the threat, the
“seduction,” as Trans Studies scholar Cassius Adair puts it, of gender
transgression?

Speaking on trans erotics, and specifically “trans for trans” or "t4t
erotics," Adair asks, "Why shouldn't transness be transmissible or
contagious? Why can't the erotic be a site of producing trans identity
or practices?" He points out that, after all, cis people do it all the
time: they use sexuality and sexual encounters as sites of identity
formation.

SLIDE 17 - THANKS AND CONTACT

Thank you.

And for those of you who want to follow this work, you can find me on
Github and HuggingFace under the username, Gofilipa. 

** bank
*** bill titles and declarations:
Federal bills:
- US HB1064: Ensuring Military Readiness Act of 2023
  - disqualifies transgender persons from military service
- US HB1276: Protect Minors from Medical Malpractice Act of 2023
  - doctors to be liable to all adverse effects (physical,
    psychological, etc) following trans-affirming care
- US HB1399: Protect Children’s Innocence Act
  - gender-affirming care on minors to be a felony
- US HB1490: Preventing Violence Against Female Inmates Act of 2023
  - incarcerating people by "biological sex"
- US HB216: My Child, My Choice Act of 2023
  - schools to obtain written parental consent before teaching
    anything related to gender/sex/sexuality.
- US HB3101: TPA Act Traditional Passport Act
  - passport gender designation to be binary and based on sex
- US HB3102: TSA Act Traditional Screening Application Act
  - prohibits "X" gender designation on TSA screenings


MO SB868:
- "Vulnerable Child Compassion and Protection Act"
- "No school official shall encourage a student to adopt a gender
  identity or sexual relationship."

FL H0599:
- "Gender Identity Employment Practices"
- "It is the policy of the state that a person's sex is an immutable
  biological trait and that it is false to ascribe to a person a
  pronoun that does not correspond to such person's sex."

*** defs from bills
"'Gender identity', a person's internal sense of self as male, female,
neither, both, or somewhere along the gender spectrum" (MO HB1674).

"'Gender identity', the preconceived notion of someone's psychological,
behavioral, social, and cultural aspects of being a biological male or
biological female" (MO SB868).

"'Sex', the physical condition of being male or female based on
genetics and physiology, as identified on the individual's original
birth certificate" (MO HB1674).

"'Biological sex', an individual's sex as assigned at birth on his or
her original birth certificate... or, if the individual's birth
certificate is unobtainable, another government record" (MO SB868).

It must be the policy of every public K-12 educational institution
that is provided in this State that the sex of a person is an
immutable biological trait and that it is false to ascribe to a person
a pronoun that does not correspond to such person's sex. This section
does not apply to individuals born with a genetically or biochemically
verifiable disorder of sex development, including, but not limited to:

            (1) 46, XX disorder of sex development;

           (2) 46, XY disorder of sex development;

           (3) sex chromosome disorder of sex development;

            (4) XX or XY sex reversal; and

            (5) ovotesticular disorder.

*** closing on adair and segwick
Adair here does for contagion what Sedgwick does for shame: turns
something that is traditionally seen as a negative into something that
may be generative and productive. Taking something that has been a
tool of oppression, and turning it into a creative resource.

Sedgwick explains that this kind of reading, reparative reading,
exposes “the ways selves and communities succeed in extracting
sustenance from the objects of a culture—-even of a culture whose
avowed desire has often been not to sustain them” (Touching Feeling
151).
