** BANK

Bias is not neutral. 
- Devinney et al 2022: "Masculine and feminine genders are also
  generally presented as “opposites" which can be “swapped" for
  each other; placed on each end of a linear scale of bias; or
  used to define vector space directions."

- Devinny et al 2022: on "beards"
  - "There may be a statistically strong association between
    masculine nouns and beards, and beards are often a part of
    masculine performativity, but that does not make it a
    foolproof indicator of gender for an individual... The
    particular example of beard with “male nouns” is also
    ironic, as beard can in specifically refer to a woman whom
    a gay man is dating to hide his sexuality – making it a
    feminine noun in these cases... We must know... what
    discourse (the beard on someone’s face, or the beard they
    are dating?) make up the context to make a judgement about
    how meaningful a particular sentence or association is."



data contexts: gender
- calling for interdisciplinarity, specifically incorporating
  Feminist, Gender, and Queer Studies into NLP (Devinney et al
  2022). 
- theories of gender, Butler, Prosser, etc
- close readings of definitions of gender from the dataset
- small words like "regardless" reifying binaries 

data contexts: trans
- trans studies investments, trans vs queer
- transphobia based on contagion
- transphobia in bill titles? 
** bias is one dimensional
- [ ] Bias is one dimensional
  - [ ] Equalized Odds[fn:11] measures how well models perform, how
    "accurate" they are, prompted by different identities.
    - Nemani et al 2023: "measures the degree to which a model’s
      predictions are equal across different demographic groups, such
      as males and female. In the context of gender bias, the metric
      can be used to assess whether the model is making equally
      accurate predictions for male and female inputs."
  - [ ] May et al 2019: They apply WEAT to sentence level tests, enabling
    them to explore complex kinds of intersectional bias (citing hooks
    and Crenshaw) and find the method unreliable perhaps due to
    difficulty in simplifying concepts/contexts in sentence-level
    inputs.
  - [ ] FISE procedure (Charlesworth et al 2024).
    - “Interestingly, the data show less support for class-centrism,
      i.e. rich does not dominate frequencies in language to the same
      extent that White supersede Black, or men supersede women. For
      example, *Black Poor* (6% of traits) and *Black Rich* (5% of
      traits) are similar in frequency showing that the low frequency
      of traits associated with *Black* is not altered even after
      including the dominant class group *Rich*. Perhaps class may be
      less of a marked category in language: we may be unlikely to
      point out that someone is *rich*, unless it is extreme wealth,
      because categorizing class is prone to subjective judgments of
      wealth cues ([31](javascript:;)). In contrast, race and gender
      may be relatively less ambiguous in categorizations and
      therefore more likely to be noted in language and to shape trait
      frequencies.” (Charlesworth et al 2024). 
      - makes assumptions about visibility and invisibilty of certain
	identities, like class, saying that it's not as prevalent
	because being "rich" or "poor" isn't as marked in language;
	whereas class vs race visibility has been well theorized in
	humanities.


** distributional hypothesis in WEAT
As mentioned
above, WEAT takes the distributional hypothesis in linguistics, that
"the statistical contexts of words capture much of what we mean by
meaning," and apply it to computer science (Caliskan et al 2017). The
idea is that the word embeddings, which represent word meaning in
numerical form, translate the "statistical contexts" of words into the
vector space of about 300 dimensions, in the case of the Global
Vectors for Word Representation (GloVe) model. 

** trans studies on class
Trans Studies problematizes the sex/gender binary

Trans Studies 

Intersectionality. 



[fn:9] Raha, Nat. 2015. "The Limits of Trans Liberalism." London:
Verso.
https://www.versobooks.com/en-gb/blogs/news/2245-the-limits-of-trans-liberalism-by-nat-raha.

